### ISSUE TITLE
Does not work with Lucene 4.2 due to IndexWriter.MaxFieldLength dependency in LuceneUtils

### ISSUE THREAD

**Issue by GoogleCodeExporter** [semanticvectors/semanticvectors#63]
```
What steps will reproduce the problem?

Running semanticvectors version 3.8 with Lucene version 4.2.0

What is the expected output? What do you see instead?

NoClassDefFoundError at LuceneUtils.compressIndex (Line 381)

What version of the product are you using? On what operating system?
SemanticVectors version - 3.8
Lucene Version - 4.2
OS - Windows 7

Please provide any additional information below.


```

Original issue reported on code.google.com by `mishra9m...@gmail.com` on 1 Apr 2013 at 8:21
- Merged into: #65
